packages:
  - apps/*
  - packages/*

catalog:
  "@biomejs/biome": 2.2.2
  "@t3-oss/env-core": 0.13.8
  "@tailwindcss/postcss": 4.1.12
  "@types/node": 24.3.0
  "@types/react": 19.1.11
  "@types/react-dom": 19.1.7
  next: 15.4.5
  react: 19.1.1
  react-dom: 19.1.1
  tailwindcss: 4.1.12
  turbo: 2.5.6
  typescript: 5.9.2
  wrangler: 4.32.0
  zod: 4.1.1
